### ISSUE TITLE
Install fails on Windows

### ISSUE THREAD

**Issue by vjrantal** [Level/leveldown-mobile#9]
I am testing following on a Windows 10 machine with Visual Studio 2015 installed:

```
$ jx npm install leveldown-mobile
npm http request GET https://registry.npmjs.org/leveldown-mobile
npm http 304 https://registry.npmjs.org/leveldown-mobile
npm http request GET https://registry.npmjs.org/bindings
npm http request GET https://registry.npmjs.org/fast-future
npm http request GET https://registry.npmjs.org/abstract-leveldown
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/fast-future
npm http 304 https://registry.npmjs.org/abstract-leveldown
npm http request GET https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/xtend

> leveldown-mobile@1.1.1 install C:\Users\vjrantal\AppData\Local\Temp\foo\bar\node_modules\leveldown-mobile
> ""C:\Program Files (x86)\JXcore\jx.exe" C:\Users\vjrantal\.jx\npm\node_modules\node-gyp\bin\node-gyp.js rebuild"

gyp JXcore NODE-GYP Using node-gyp bundled in npm coming from JXcore
gyp ERR! NPMJX did not provide NVM_NODEJS_ORG_MIRROR url
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Parameter 'url' must be a string, not undefined
gyp ERR! stack     at Url.parse (url.js:88:11)
gyp ERR! stack     at urlParse (url.js:82:5)
gyp ERR! stack     at Object.urlResolve [as resolve] (url.js:385:10)
gyp ERR! stack     at resolveLibUrl (C:\Users\vjrantal\.jx\npm\node_modules\node-gyp\lib\process-release.js:125:18)
gyp ERR! stack     at processRelease (C:\Users\vjrantal\.jx\npm\node_modules\node-gyp\lib\process-release.js:98:14)
gyp ERR! stack     at configure (C:\Users\vjrantal\.jx\npm\node_modules\node-gyp\lib\configure.js:32:17)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (C:\Users\vjrantal\.jx\npm\node_modules\node-gyp\lib\node-gyp.js:66:37)
gyp ERR! stack     at run (C:\Users\vjrantal\.jx\npm\node_modules\node-gyp\bin\node-gyp.js:72:30)
gyp ERR! stack     at process._tickCallback (node.js:917:13)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files (x86)\\JXcore\\jx.exe" "C:\\Users\\vjrantal\\.jx\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\vjrantal\AppData\Local\Temp\foo\bar\node_modules\leveldown-mobile
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN ENOENT ENOENT, open 'C:\Users\vjrantal\AppData\Local\Temp\foo\bar\package.json'
npm WARN EPACKAGEJSON bar No description
npm WARN EPACKAGEJSON bar No repository field.
npm WARN EPACKAGEJSON bar No README data
npm WARN EPACKAGEJSON bar No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\JXcore\\jx.exe" "C:\\Users\\vjrantal\\.jx\\npm\\bin\\npm-cli.js" "--loglevel" "http" "install" "leveldown-mobile"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! leveldown-mobile@1.1.1 install: `""C:\Program Files (x86)\JXcore\jx.exe" C:\Users\vjrantal\.jx\npm\node_modules\node-gyp\bin\node-gyp.js rebuild"`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the leveldown-mobile@1.1.1 install script '""C:\Program Files (x86)\JXcore\jx.exe" C:\Users\vjrantal\.jx\npm\node_modules\node-gyp\bin\node-gyp.js rebuild"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown-mobile package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ""C:\Program Files (x86)\JXcore\jx.exe" C:\Users\vjrantal\.jx\npm\node_modules\node-gyp\bin\node-gyp.js rebuild"
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown-mobile
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vjrantal\AppData\Local\Temp\foo\bar\npm-debug.log
```

Information about my jx installation:

```
$ jx -jxv
v0.3.1.1
$ jx -jsv
Google V8 v3.14.5.9
$ jx npm --version
3.3.12
```

**Comment by vjrantal** [comment]
@obastemur: Some further information on a machine that has both Visual Studio 2013 and 2015 installed.

When I had JXcore 0.3.1.0 installed, `jx npm install leveldown-mobile` worked correctly. After I upgraded to JXcore 0.3.1.1, I got the same error as above. So, based on this testing, the latest JXcore release seems to have introduced this issue. Could that be possible?

**Comment by vjrantal** [comment]
@obastemur: Furthermore, I just got the same error also on my Mac with the latest JXcore release..

**Comment by obastemur** [comment]
This is not a leveldown-mobile issue.

> gyp ERR! NPMJX did not provide NVM_NODEJS_ORG_MIRROR url
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Parameter 'url' must be a string, not undefined
gyp ERR! stack     at Url.parse (url.js:88:11)
gyp ERR! stack     at urlParse (url.js:82:5)

/cc @ktrzeciaknubisa 

closing from here.
